# NOTE: All paths relative to root of repository
app:
  SECRET_KEY: 94c75b0757c0dc592d1cf5b877443d2ccc412561136abdd7246af32dad76365a
  # generate a new key for security
  USE_SESSION_FOR_NEXT: True
  
  # used by login
  GOOGLE_API_KEY: 773b951aa8457a0c6d0de74fa4687701e5b603c4829c6bce244e171884a640e3
  # Used by google servers for authenticating user
  
  UPLOADS:
    directory: /app/run/uploads/submitted
    pending_directory: /app/run/uploads/pending
    allowed_extensions: ['png', 'jpg', 'jpeg', 'txt', 'data', 'log.xml', 'xml', 'pdf', 'doc', 'docx', 'svg']
  
  DATABASE:
    dialect: postgresql
    driver: psycopg2
    username: postgres
    password: pg2access
    host: 'postgres'
    port: 5432
    database: datams
  
  CELERY:
    broker_url: 'redis://redis:6379/0'
    result_backend: 'redis://redis:6379/0'
    task_ignore_result: True
    # celery_imports: ('datams.redis',)
  
  REDIS:
    host: 'redis'
    port: 6379
    decode_responses: True
    
map:
  MOORING_ICON: ./datams/static/icons/hydrophone.svg
  # Icon used on maps to display hydrophones

menu:
  EQUIPMENT_ITEMS: 
    - Acoustic Release
    - Acoustic Release Deck Unit
    - Battery Pack
    - Hydrophone
    - Hydrophone (Archival)
    - Hydrophone (Real-Time)
    
  EQUIPMENT_STATUS:
    - Active
    - Available
    - Deployed
    - Loaned
    - Lost At Sea
    - Maintenance Required
    - Unknown
    
  CONTACT_POSITIONS:
    - Analyst
    - Project Manager
    - Equipment Manager
    - Executive Director
    - Fisheries Acoustician
    - Strategic Manager
    - Strategic Ocean Lead
    - Team Leader
    - Organization Manager
    - Vessel Crew (Recovery)
    - Vessel Crew (Deployment)
    - Senior Research Technician
    - Senior Research Scientist
    - Senior Data Scientist
    - Scientific Programmer
    - Marine Biologist
    - Mechanical Engineer
    - Research Technician
    - Principal Fisheries Officer
    - Technical Coordinator Sustainable Fisheries
    - Technical Coordinator
    - Ecologist
    - Principal Research Scientist
    - Project Coordinator
    - Hardware Engineer
    - Vertebrate Ecologist
    - Other
  
  FILE_DESCRIPTIONS:
    - Acceleration Data
    - Audio Data
    - Logging Data
    - Temperature Data
    - Field Data Sheets
    - Compressed SoundTrap Data
    - Analysis File
    - Report
    - Other
    
